### ISSUE TITLE
패키지에 hook 사용시 Invalid Hook Call Warning 에러

### ISSUE THREAD

**Issue by milooy** [EveryAnalytics/react-analytics-provider#1]
https://github.com/transitive-bullshit/create-react-library#use-with-react-hooks

**Comment by jhlee910609** [comment]
https://github.com/facebook/react/issues/13991#issuecomment-435587809

**Comment by jhlee910609** [comment]
러이브러리 패키징할 때의 리액트 모듈이랑 데모 빌드용 리액트 모듈이랑 두 가지 모듈이 공존해서 생긴 문제인듯 합니다. 문제는 찾았으니 트러블슈팅 해보겠습니다. @milooy
