### ISSUE TITLE
PR형식 추가

### ISSUE THREAD

**Issue by milooy** [EveryAnalytics/react-analytics-provider#115]
https://github.com/meshkorea/front-end-engineering/blob/main/conventions/commit/index.md 참고

**Comment by greatSumini** [comment]
오 [Contributing[(https://github.com/EveryAnalytics/react-analytics-provider/blob/main/CONTRIBUTING.md) 에 포함해도 좋을 것 같습니다!

**Comment by milooy** [comment]
오 굿굿~ PR템플릿에 녹여낼게요!
