### ISSUE TITLE
demo 폴더에서 npm install 시 에러

### ISSUE THREAD

**Issue by MiryangJung** [EveryAnalytics/react-analytics-provider#129]
demo 폴더 내에서 npm install 시 `Cannot find name 'require'` 에러가 생김
package.json이 한 프로젝트 폴더내에 두 개가 존재하여서 충돌나는 것으로 추측

**Comment by jhlee910609** [comment]
@MiryangJung 혹시 `/demo` 폴더에서 직접 `npm install` 했을때, 발생하는 건가요?

**Comment by MiryangJung** [comment]
@jhlee910609  `/demo/with-cra` 에서 발생합니다! 
제가 여러번 테스트해본 결과 `package.lock.json` 을 지우고 `npm install` 을 하면 에러가 나지 않더라구요. path가 꼬인 듯합니다.

path와 dest가 달라서 꼬인 느낌적인 느낌...

```
npm ERR! code ENOENT
npm ERR! syscall rename
npm ERR! path /project/demo/with-cra/node_modules/.staging/js-tokens-41ac2488
npm ERR! dest /project/node_modules/react-dom/node_modules/js-tokens
```
