### ISSUE TITLE
테스트 커버리지 관리

### ISSUE THREAD

**Issue by greatSumini** [EveryAnalytics/react-analytics-provider#13]
codecov, coveralls 등을 사용해 관리해봐도 좋을 것 같습니다!

**Comment by josworks27** [comment]
커버리지 서비스 사용해 본 적은 없지만, 개인적으론 codecov가 기능적인 면이나 깃헙 연동에 있어서 좋아보이네요!
https://docs.codecov.com/docs/flags

단점으로 비교되는 가격도 오픈소스 프로젝트는 무료 🥰
https://about.codecov.io/pricing/
