### ISSUE TITLE
googleAnalytics.initialize 테스트 작성

### ISSUE THREAD

**Issue by greatSumini** [EveryAnalytics/react-analytics-provider#130]
## Description

utils/googleAnalytics/initialize.ts의 테스트를 작성합니다.
요구사항은 아래와 같습니다.

1. jest를 사용한 유닛 테스트로 작성합니다.
2. 필요에 따라 적절히 mocking합니다.
3. coverage를 할 수 있는한 높게 유지합니다.

**Comment by jhlee910609** [comment]
@greatSumini 저희가 구현한 ga event wrapper 함수들도 테스트 코드를 추가해두면 좋을까요? 👀

**Comment by greatSumini** [comment]
앗 그렇네요 ㅎㅎ.. 일단 아직 온전한 테스트 코드가 없는 상황이라 이번주..?까지만 테스트셋업길드에서 이리저리 부딪혀가며 틀을 잡아볼까하고 있습니다 ㅎㅎ 최대한 빠르게!! 준비해서 PR 열어보면 리뷰과정에서 같이 디벨롭해봐도 좋을 것 같아요 😃

**Comment by jhlee910609** [comment]
@greatSumini 네! 좋습니다 :)
