### ISSUE TITLE
googleAnalytics.click 테스트 코드 작성

### ISSUE THREAD

**Issue by josworks27** [EveryAnalytics/react-analytics-provider#133]
# 개요
googleAnalytics.click의 테스트 코드를 작성합니다.

# 방법
* 핵심 함수인 gtag을 모킹하여 인자가 잘 들어가는지 확인합니다.

# 참고
* https://github.com/EveryAnalytics/react-analytics-provider/discussions/128

**Comment by greatSumini** [comment]
closed via #167
