### ISSUE TITLE
demo에서 @every-analytics/react-analytics-provider import 하기 쉽게 수정

### ISSUE THREAD

**Issue by uoon-dev** [EveryAnalytics/react-analytics-provider#153]
Demo에서 사용할 때

@every-analytics/react-analytics-provider
1. import suggestion 정리
2. type import 시 eslint 에러 수정

**Comment by jhlee910609** [comment]
@uoon-dev 관련 PR merged 됐는데, 해당 이슈 닫으셔도 될 것 같아요!
