### ISSUE TITLE
nextjs demo app에 emotion 적용

### ISSUE THREAD

**Issue by hy57in** [EveryAnalytics/react-analytics-provider#161]

**Comment by jhlee910609** [comment]
@hy57in 저희 `with-cra`에도 emotion-js 사용하고 있나요? 👀

**Comment by hy57in** [comment]
> @hy57in 저희 `with-cra`에도 emotion-js 사용하고 있나요? 👀

헉 아닌가요,, WAH와 헷갈렸나봅니다 ㅜ

**Comment by jhlee910609** [comment]
@hy57in ui styling의 필요성도 아젠다로 같이 논의해보면 좋을 것 같아요~
