### ISSUE TITLE
te-jest 제외하기 

### ISSUE THREAD

**Issue by p-iknow** [EveryAnalytics/react-analytics-provider#177]
## 관련 이슈 
![image](https://user-images.githubusercontent.com/35516239/131250124-d084d9f9-f383-4e7f-8b17-6125e148e5e0.png)
- type-error 의 경우 ci의 type check에서 잡기 때문에, 테스트코드에  type-error 때문에 test가 fail 되게 할 필요가 없습니다.
- te-jest를 쓰지 않으면 속도가 아주 약간 빨라집니다. 

## te-jest 를 사용하는 이유
- ts-jest 를 쓰지 않고 일반 jest 를 쓰면 type error가 있어도 test가 실패하지 않습니다. 

## Action Item 
- ts-jest를 쓰지 않도록 세팅한다.

**Comment by greatSumini** [comment]
ts-jest가 typescript 및 jsx transform도 겸하고 있어서, 제거했을 때 이를 대체할 패키지를 2개 이상 설치해야할 것 같습니다!
성능에 큰 차이가 없다면 그냥 두는 것도 나름 간결?해서 좋겠다는 생각이 드는데.. 혹싀 어떻게 생각하시나용 ?.?

**Comment by p-iknow** [comment]
^저 이거 어제 맥락을 잘못이해한 것 같은데 , 타입에러를 신경쓰지 않겠다는 의미가, 런타임에서 타입체크에 관한 코드를 넣지 않겠다이더라구요.
그런거라면 ts-jest를 뺄 이유는 없는 것 같습니다. 

+ 위와 무관하게 `jsx/transform` 별도 추가는 안해도 되요. jest 가 babel을 돌려서  쿵짝쿵짝 하기 때문에, 사내에서도 ts-jest 빼고 쓰고 있긴 합니다.

이슈는 클로즈 하겠습니다.
