### ISSUE TITLE
[bug] LICENSE is not reflected to npm package (0.2.0)

### ISSUE THREAD

**Issue by greatSumini** [EveryAnalytics/react-analytics-provider#208]
![Screen Shot 2021-09-11 at 4 54 12 PM](https://user-images.githubusercontent.com/48555121/132940820-80a72825-83be-4494-a890-f67740c819ce.png)

분명 MIT로 잘 작성되어있고, `.npmignore`에도 포함시키지 않았는데 이상하네요.. :sob:

**Comment by josworks27** [comment]
package.json에 "license": "ISC" 때문인 것 같습니다 ~!
