### ISSUE TITLE
demo앱에 SSR 예시 추가

### ISSUE THREAD

**Issue by milooy** [EveryAnalytics/react-analytics-provider#21]
현재는 SPA예시만 있다~
추후에 SSR(Next.js등) 예시 추가. demoSSR 등 폴더 만들어서?

**Comment by greatSumini** [comment]
[vercel/next.js](https://github.com/vercel/next.js/tree/canary/examples) 처럼 examples 폴더를 만들어서 with-cra, with-nextjs, with-gatsbyjs 등으로 분류해도 좋을 것 같아요 😊

**Comment by milooy** [comment]
베리베리 굿아이디어

**Comment by greatSumini** [comment]
closed via #56
