### ISSUE TITLE
Prevent amplitude import in server-side rendering environment

### ISSUE THREAD

**Issue by jhlee910609** [EveryAnalytics/react-analytics-provider#212]
<img width="1186" alt="image" src="https://user-images.githubusercontent.com/28521282/134774696-8c17e6e9-9c89-4d19-af32-0fd3b5c5d4e6.png">

## 문제
 - npm에 publish된 0.2.0 version 기준입니다.
 - Server-Side-Rendering(이하 SSR) 환경에서 window 객체가 없어 amplitude 관련 모듈이 정상 동작하지 않습니다.
 - [amplitude 공식 문서](https://help.amplitude.com/hc/en-us/articles/115000959052-For-developers-Getting-started#h_c2eacd03-f809-47d6-8abb-e82616eb59c6)에 따르면 SSR에서 event tracking 하고 싶으면 직접 amplitude 측에서 제공해주는 api로 관련 정보를 보내라고 언급되어 있습니다.
    - 많은 이들이 같은 [문제](https://github.com/amplitude/Amplitude-JavaScript/issues/138 )를 겪고 있었습니다. 😢 

## 해결책
- SSR 환경에서 import 되지 않도록 합니다.
- 혹은 amplitude 관련 모듈 및 util function들을 제거하고, 사용자가 알아서 사용하도록 합니다.

**Comment by jhlee910609** [comment]
- amplitude 관련 모듈을 제거하는 게 맞는건가 싶기도 합니다.

**Comment by jhlee910609** [comment]
- [SSR과 CSR의 차이](https://velog.io/@seunghwa17/SSR-vs-CSR)

**Comment by jhlee910609** [comment]
- [Amplitude-Node](https://github.com/amplitude/Amplitude-Node)

**Comment by milooy** [comment]
요런식으로 하면 돼요!
```
export const useInitAmplitude = ({ onInit }: { onInit(): void }) => {
  useEffect(() => {
    if (typeof window !== undefined) {
      import('amplitude-js')
        .then((ampPackage) => {
          amplitudeInstance = ampPackage.getInstance();
          amplitudeInstance.init(process.env.NEXT_PUBLIC_AMPLITUDE_KEY as string);
          onInit();
        })
        .catch(() => null);
    }
  }, []);
};
```

**Comment by jhlee910609** [comment]
@milooy 제가 가져가서 한번 해볼게요~

**Comment by jhlee910609** [comment]
@milooy 근데 amplitude initialize 함수가 아래와 같이 일반 ts file에 선언되어 있는 함수인데, hook으로 감싸줘야하는 특별한 이유가 있나요? 

```typescript
import amplitude, {AmplitudeClient, Config} from 'amplitude-js';

export const initialize = (
  apiKey: string,
  userId?: string,
  config?: Config,
  callback?: (client: AmplitudeClient) => void,
) => {
  // eslint-disable-next-line import/no-named-as-default-member
  amplitude.getInstance().init(apiKey, userId, config, callback);
};
```

**Comment by milooy** [comment]
제가 첨부한 코드는 
SSR에 따라 amplitude 패키지 import여부부터 결정하는 코드예요~ (개인플젝에서 구현해뒀던거 그대로 복붙해옴)
저희상황에 맞게 변경해서 쓰면 됩니다.

위에서 useEffect만 빼도 되지 않을까요?

**Comment by milooy** [comment]
위 언급된 코드에 Fix 올렸습니다~
