### ISSUE TITLE
Bug: In Demo-cra, can not use mock data json.

### ISSUE THREAD

**Issue by SenseCodeValue** [EveryAnalytics/react-analytics-provider#237]
### 1. Path Error : which falls outside of the project src/ directory. 
![image](https://user-images.githubusercontent.com/59507527/138601566-959e7f29-0953-4aa1-8aa6-52d04bbba147.png)
bug is mock folder path is under with-cra. So need to move to src.

### 2. TypeScript error: need corresponding type declarations.
![image](https://user-images.githubusercontent.com/59507527/138601690-1d5c82c9-71ec-4fa3-bc5a-f07f0e2b86cf.png)
check include in tsconfig.json. 
```
{
  "compilerOptions": {...},
  "include": [
    "src",
    "typings"
  ]
}
```
declarations can be written under typings folder.
so corresponding type declarations about json in with-cra/typings.

```
// declarations about json
declare module '*.json' {
  const value: any;
  export default value;
}

```

```
// when using json
import * as Category from '..../data.json';
```

**Comment by greatSumini** [comment]
resolved. [ref](https://github.com/EveryAnalytics/react-analytics-provider/pull/238#issuecomment-955129067)
