### ISSUE TITLE
BUG: If an event occurs before the gtag is initialized, a bug occurs.

### ISSUE THREAD

**Issue by SenseCodeValue** [EveryAnalytics/react-analytics-provider#255]
The bug occurred because the product was changed after browser events such as refresh, but gtag was not initialized.

![image](https://user-images.githubusercontent.com/59507527/140636346-9da5eadc-b203-4a27-bbde-f5a623d4127d.png)

**Comment by SenseCodeValue** [comment]
새로고침 등의 브라우저 이벤트 이후 상품이 변경되어 gtag event가 발생했지만 초기화되지 않아 생긴 버그입니다.
view_item_list가 발생했지만 초기화되어 있지않아 발생하는 에러로 보입니다. 
저번에 찬희님이 알아보신바로는 page_view는 자동으로 처리가 되지만 이외의 event에대해서는 대응이 필요해보입니다.

**Comment by greatSumini** [comment]
I think it's duplicate with #34
