### ISSUE TITLE
formatOnSave와 codeActionsOnSave를 모두 true로 해도 괜찮을까?

### ISSUE THREAD

**Issue by milooy** [EveryAnalytics/react-analytics-provider#28]
formatOnSave를 false하지 않으면
eslint와 prettier가 충돌할 수 있다 알고있슴

근데 false로 하면 저장시 포매팅이 안됨

Need researxh

관련 논의 스레드
https://github.com/EveryAnalytics/react-analytics-provider/pull/24#discussion_r688969305

**Comment by p-iknow** [comment]
@milooy  요거 [eslint prettier plugin](https://github.com/prettier/eslint-plugin-prettier) 와 [eslint-prettier-config](https://github.com/banksalad/styleguide/blob/master/web/migration-guide.md#4-eslint-%EC%84%A4%EC%A0%95) 쓰면  eslint 가 prettier rule 을 받아서 처리해줘서  lint fix 시에 prettier 까지 같이 수정되서 충돌이 해결됩니다.

**Comment by milooy** [comment]
오 굿굿 ㅎㅎ 짱짱
PR 올려주심 감사하겠슴다
