### ISSUE TITLE
demo앱에서 로깅 찍힐 때 console.info 대신 toast로 보여주기

### ISSUE THREAD

**Issue by milooy** [EveryAnalytics/react-analytics-provider#33]
**As-is**

![image](https://user-images.githubusercontent.com/3839771/129471638-dd427ca3-4553-4535-b664-5f540b48088e.png)

개발자 콘솔을 열어야만 log가 잘 쌓이는지 확인 가능

**To-be**

Toast나 Alert나 혹은 화면 옆에 log가 쌓이는걸 보여줘서
개발자 콘솔을 열지 않고도 로그가 잘 찍힌다는걸 확인할 수 있도록.

**Comment by jhlee910609** [comment]
@milooy 직접 구현하나요? 아니면 괜찮은 library 사용해도 되는건가요?

**Comment by milooy** [comment]
데모 앱이라 라이브러리 써도 무상관입니다 ㅎㅎ

**Comment by jhlee910609** [comment]
@milooy 그렇담!!! 귀엽고, 예쁜 걸로 찾아서 넣겠습니다.
