### ISSUE TITLE
initialize되기 전에 event가 불릴때 처리가 안되었다

### ISSUE THREAD

**Issue by milooy** [EveryAnalytics/react-analytics-provider#34]
![image](https://user-images.githubusercontent.com/3839771/129472895-3dd9ddde-509c-480d-8c86-982a9cde7a72.png)

initialize가 된걸 확인 후 pageview든 click이든 뭐든 불려야함 ㅠㅠ

**Comment by SenseCodeValue** [comment]
만약 이러한 문제가 발생될때는 어떤식으로 보통 처리해야되나요?
1. initialized 되기전에는 event를 그냥 막는다.
2. Queue 비슷한 것에 담아서 처리한다.
어떻게 될지 너무 궁금합니다!

**Comment by jhlee910609** [comment]
@SenseCodeValue 저도 정확히는 모르겠지만 그래도 1번 방법 같은 경우에는 그렇게 되면 트래킹 되어야할 이벤트가 트래킹 되지 않기 때문에 지양하는 게 좋을 것 같아요!

**Comment by SenseCodeValue** [comment]
@jhlee910609 맞아요! 확실히 1번은 조금...아쉬울것 같네요ㅠ

**Comment by chanheeis** [comment]
https://developers.google.com/analytics/devguides/collection/ga4/page-view
![image](https://user-images.githubusercontent.com/53820773/130347988-1e7b9f7e-b69a-4ffb-8b90-7803359598a5.png)

**Comment by milooy** [comment]
GA는 자동 페이지뷰덕에 문제가 없어도 다른 이벤트들에는 이슈있을수 있겠네유
