### ISSUE TITLE
prettier setting

### ISSUE THREAD

**Issue by jhlee910609** [EveryAnalytics/react-analytics-provider#4]
- prettier
- eslint

+)  husky 설정 추가 (위 두 가지 완료 후, 여유가 있다면 시도 / 없다면 이슈 분리하여 시도)

**Comment by milooy** [comment]
허스키는 둘째치고도 1, 2는 최대한 빨리 적용하면 좋겠어요 ㅋㅋ 
일요일 릴레이 라이브 코딩 전까지 어떨까요?

**Comment by jhlee910609** [comment]
@milooy 한번 시도해볼게요~

**Comment by jhlee910609** [comment]
@milooy lint style은 standard로 우선 해둘까요?

**Comment by milooy** [comment]
네 standard도 좋구.. eslint:recommended 는 어때요~? ㅎㅎ

**Comment by jhlee910609** [comment]
@milooy 네, 상관 없을 것 같아요! 😄  금주 토요일을 due date로 잡고 진행해볼게요.
