### ISSUE TITLE
querystring이 바뀌어도 라우트 페이지 리렌더링이 안됨 

### ISSUE THREAD

**Issue by milooy** [EveryAnalytics/react-analytics-provider#44]
products?color=red -> products?color=yellow

컨텐츠가 안바뀜

**Comment by greatSumini** [comment]
RAP 이슈인 것 같아 옮겼습니다!

**Comment by jhlee910609** [comment]
@milooy 어제 말씀하신대로 `react-router-dom` 사용할 건가요? 👀
