### ISSUE TITLE
README 꾸미기

### ISSUE THREAD

**Issue by greatSumini** [EveryAnalytics/react-analytics-provider#59]
## 할 일들

1. 내용 보강
    - 간략한 설명
    - 장점 list [참고](https://github.com/laymonage/giscus#readme)
    - handbook으로의 링크
2. 뱃지 추가 (npm version, bundle size, ci passing, github star?)
3. Getting Started
4. Usages
5. Contributors
6. License
7. Contributing

## Help Wanted 👀 

완전 대문이라 영어로 작성하는 것도 좋을 것 같은데, 핸드북이나 각종 콘솔로그들이 완전 한글 위주니 굳이..?라는 생각도 듭니다.
다들 어떻게 생각하시나요??

**Comment by NamNamju** [comment]
그 지난번 회의에서, 국제화 계획을 위해 마스터 시작 때부터 영어로 커밋하자고 하셨던 것 같아요.
그것처럼 일단 한글로 작성하되, 추후에 수정하는(혹은 추가 작성하는) 계획은 어떠신지요?

**Comment by greatSumini** [comment]
@NamNamju 아하 넵 일단 한글로 작성해놓고 나중에 전면 국제화 도입할 때 수정하는 것도 좋겠네요 ㅎㅎ 조언 감사합니다! 🙇‍♂️

**Comment by hiphapis** [comment]
우선 초안은 한글로 작성하지만, 배포는 영어도 같이 나가는게 좋을 것 같아요.
더불어 한/영 문서는 어떤 방식으로 관리할 것인지 논의도 필요해보여요.
예를들어
`README.ko.md`, `README.en.md` 등등이죠.
아니면 깃헙안에 위키 페이지 등록도 생각해볼 수 있겠죠.
방법은 많으니 ㅎㅎㅎ
길드원들과 한번 논의해보셔도 좋을 것 같아요!

**Comment by greatSumini** [comment]
아하 분리하는 것도 좋겠네요 ㅎㅎ 고민해보겠습니다 감사합니다 :-)

**Comment by greatSumini** [comment]
@all-contributors please add @milooy for code

**Comment by greatSumini** [comment]
@all-contributors please add @greatSumini for code
