### ISSUE TITLE
package-lock.json 정리

### ISSUE THREAD

**Issue by hiphapis** [EveryAnalytics/react-analytics-provider#63]
추측하기론 `--legacy-peer-deps` 를 해야만 하는 상황 때문이지 않나 싶어요.
어떤 package때문인지 찾아내고, `--legacy-peer-deps` 없이 할 방법이 없는지 혹은 대체 package는 없는지 확인 및 수정하면 좋을 것 같아요.

좀 전에 feat/48 쫑 푸는거 작업할려고 새로 npm i 해보니.. package-lock.json이 6만줄이 넘어요 ㅠ,.ㅠ

**Comment by greatSumini** [comment]
와 6만.. 심각하네요 😭
