### ISSUE TITLE
CODE_OF_CONDUCT.md 작성

### ISSUE THREAD

**Issue by NamNamju** [EveryAnalytics/react-analytics-provider#72]
# 작성 내용

# 행동 규범(Code of Conduct)

## 서약

본 프로젝트의 기여자(contributor) 및 메인테이너(maintainer)는 개방적이고 친근한 환경을 조성하기 위해 나이, 신체, 장애, 경험 수준, 국적, 외모, 인종, 종교, 성적 정체성 및 성향에 관계없이 모든 사람이 본 프로젝트에 참여할 수 있도록 최선을 다할 것을 서약합니다.
우리는 이슈 보고, 기능 요청, 문서 업데이트, 풀 리퀘스트(pull request) 또는 패치(patch) 제출, 그리고 기타 다른 활동으로 기여하는 모든 분들을 존중할 것을 서약합니다.

## 표준

기여자가 해야 할 행동은 다음과 같습니다.

- 바르고 고운 언어 사용하기
- 서로 다른 관점과 경험을 존중하기
- 열린 마음을 가지고 건설적인 비판을 수용하기
- 커뮤니티에 가장 도움이 되는 것이 무엇인지 생각하기
- 다른 커뮤니티 구성원들의 의견에 대한 공감을 표현하기
- 이해와 존중을 기반한 원활한 소통하기

기여자가 하지 말아야 할 행동은 다음과 같습니다.

- 성적인 언어 또는 이미지를 사용하거나, 불쾌한 성적 관심 또는 접근을 할 경우
- 불필요한 논쟁을 할 경우
- 모욕적 또는 비하하는 댓글을 남길 경우
- 사적인 또는 정치적인 공격을 할 경우
- 공개적이거나 사적인 괴롭힘을 할 경우
- 동의없이 타인의 집주소 또는 전자주소 등의 개인 정보를 공개할 경우
- 그 외에 부적절한 것으로 간주될 수 있는 다른 행위
- 위와 같은 상황들을 방관할 경우

## 책임

프로젝트 메인테이너는 행동의 기준을 명확히 해야 할 책임이 있습니다. 또한, 용납 되어질 수 없는 행위들에 대해 적절하고 공정한 시정 조치를 취할 책임이 있습니다.
프로젝트 메인테이너는 본 행동 규범에 부합하지 않거나 부적절한 것으로 간주되는 코멘트, 커밋, 코드, 위키 편집, 이슈와 다른 기여들에 대해 삭제, 수정 또는 거부할 수 있는 권한을 가지고 있습니다. 또한, 이외에 옳지 못한 행동을 한 기여자를 일시적 또는 영구적으로 퇴장시킬 수 있습니다.
프로젝트 메인테이너는 프로젝트 관리의 모든 관점에서 이러한 행동 규범 원칙을 공정하고 일관되게 적용할 것을 약속해야 합니다. 행동 규범을 준수하지 않거나 시행하지 않는 프로젝트 메인테이너는 프로젝트팀에서 영구적으로 제명될 수 있습니다.

## 범위

본 행동 강령은 프로젝트 활동 영역 내에서뿐만 아니라 개인이 프로젝트 또는 커뮤니티를 대변하는 경우 공공의 활동 영역에서도 적용됩니다. 이것은 공식 프로젝트 이메일 사용, 공식 소셜 미디어 계정을 통한 포스팅, 온라인 또는 오프라인에서의 행사에서 보여지는 행동을 포함합니다. 프로젝트의 대표는 메인테이너에 의해 향후 정의되어지고 명시될 수 있습니다.

## 시행

EveryAnalytics에서 발생하는 욕설, 희롱 또는 기타 용납 될 수 없는 행동은  [EMAIL 주소 입력]을 통해 신고할 수 있습니다. 모든 불만 사항은 검토 및 조사될 수 있고, 상황에 따라 적절하다고 판단되는 대응을 취할 것입니다. 프로젝트 팀은 불만 사항을 알린 리포터에 관한 비밀을 유지할 의무가 있습니다. 특정 시행 정책에 대한 자세한 내용은 별도로 게시 될 수 있습니다.

## 속성

본 행동 규범은 https://github.com/cncf/foundation/blob/master/code-of-conduct-languages/ko.md 와 https://www.contributor-covenant.org/ko/version/1/4/code-of-conduct/ 에서 영감을 받아 작성하였습니다.

# Help Wanted
행동 규범을 작성하려고 합니다. 제가 내용을 꾸려봤는데, 체크해주실 수 있으신가요?
중간에 이메일 주소 입력은 멘토님의 이메일 주소를 넣어야할지 여쭤볼 예정입니다!
(배포 이후 영어로 수정 예정)

**Comment by greatSumini** [comment]
좋은 내용이네요 ㅎㅎ 굿입니다 👍🏻
